### ISSUE TITLE
[FEATURE REQUEST] Multi Level subfolders

### ISSUE THREAD

**Issue by calvinthefreak** [chibisafe/chibisafe#191]
**Is your feature request related to a problem? Please describe.**
Ok, well now I am hosting over 80K of files on the lolisafe folder which kind of kills the Performance, you can Understand what I mean, the Inode usage is killing it.
**Describe the solution you'd like**
Is there any Possibility, that we can add an Multi-Level Directory? so if I upload a file, for example that the file is called /upload/slr93adf.jpg that we can define a level of subdirs like this: /upload/sl/r9/slr93adf.jpg and then merge it back again with the Nginx location? Maybe this will improve the Performance with big installs...
**Additional context**
Ok No screenshots here, because I already described it in detail!

**Comment by Pitu** [comment]
This is actually something I've been considering for the next version, at least for users. The idea would be to have folders based on the uuid of users and their files in there, making it lighter on the main upload folder. As for public uploads, would probably map them to the same folder regardless.

Gotta investigate how feasible this would be with nginx to have the least latency possible when looking for the file in the correct folder to retrieve it though.

**Comment by calvinc64** [comment]
I can say, that me (Single User for one thing) has over 5S Response with an SSD samsung evo 860 500gb and an I7 4770K CPU in my Server... not really good perf for this less files, but well its ext4, so what fcks given...

I rather would use an multi folder setup based on the Filename, and its not that bad to Implement I think

**Comment by BobbyWibowo** [comment]
Huh, I actually wasn't aware this was an issue (low-key implying my safe isn't popular enough to warrant so many uploads). Though I made Cloudflare to full-cache my uploads folder, so there's that.
I kinda like the idea of using the first 2 letters of the filenames as sub dir names:
`abcd.png` -> `/uploads/files/a/b/abcd.png`
There won't be much rewrite logic required for nginx to lookup the actual file paths that way, I suppose?
Also I prefer to move all those sub dirs into another subdir (named `files` for example) to avoid the horror when navigating to `uploads` directory to get a brief glance of the state of thumbs, chunks, etc dirs.

Anyway, I'll be keeping this in mind.

**Comment by Pitu** [comment]
The new lolisafe version defaults to using node to serve the files instead of nginx, so this is something that I'm looking into right now.

The reason behind this is easier setup, and the performance difference is negligible so if I can achieve an easier setup for better user experience that doesn't hinder the performance of serving the files, sounds like a good deal.

I'm open to suggestions though, first 4 letters split in 2 folders sound good at the moment since just `t/5` will get populated pretty fast leading to the same problem in the future.

**Comment by calvinc64** [comment]
Yeah, seems to be understandable, well, I will still keep serving it with Nginx, because I have a Main-Upload Server and another replicated one that are in LB config.

But I can understand that you said that you want `ab/cd` as folder structure

> first 4 letters split in 2 folders sound good at the moment since just `t/5`

Well, if I find out how to serve this via Nginx, I will let you know.

**Comment by Pitu** [comment]
This is not something we will pursue for the time being with the current v5 version
