### ISSUE TITLE
[BUG] Frontpage converts upload size to MiB not MB

### ISSUE THREAD

**Issue by NOCx420** [chibisafe/chibisafe#521]
**Describe the bug**
The frontpage uses the wrong conversion and displays wrong MB number.

**To Reproduce**
1. Go to your settings
2. Change the max size setting to a number like 500000000 bytes
3. Go to the frontpage
4. Upload box displays 476.8MB instead of 500MB

**Screenshots**
![image](https://github.com/chibisafe/chibisafe/assets/56538139/0d87d5db-3911-4873-a979-c214fbb00a9c)
![image](https://github.com/chibisafe/chibisafe/assets/56538139/f2dfd673-45ac-43ad-b952-d5243272db9d)

**Additional context**
I'm pretty much 100% sure that the byte number is getting converted to Mebibytes (MiB) and not Megabytes (MB), because if I put in the Mebibyte equivalent of 500MB, which is 524288000 bytes, the frontpage shows 500 "MB".

**Comment by 7zx** [comment]
Perhaps it's because 500,000,000 bytes equate to approximately 476.8 megabytes? Nothing seems wrong for me.

**Comment by 7zx** [comment]
> > Perhaps it's because 500,000,000 bytes equate to approximately 476.8 megabytes? Nothing seems wrong for me.
> 
> https://convertlive.com/u/convert/bytes/to/mebibytes#500000000

https://www.convertunits.com/from/byte/to/MB

**Comment by NOCx420** [comment]
> > > Perhaps it's because 500,000,000 bytes equate to approximately 476.8 megabytes? Nothing seems wrong for me.
> > 
> > 
> > https://convertlive.com/u/convert/bytes/to/mebibytes#500000000
> 
> https://www.convertunits.com/from/byte/to/MB

![image](https://github.com/chibisafe/chibisafe/assets/56538139/c22b3684-1db3-41d9-a3e8-6edf047f59b8)

1 MiB = 1 mebibyte = 1,024^2 bytes = 1,048,576 bytes;

1 MB = 1 megabyte = 1,000^2 bytes = 1,000,000 bytes;

Why not use SI prefixes? It's much more understandable.

**Comment by 7zx** [comment]
The values are nearly the same because the difference between a Megabyte and a Mebibyte is relatively small, and answering your question, i don't know, ask the owner ¯\_(ツ)_/¯

**Comment by Pitu** [comment]
Thanks for mentioning this. 
Currently we do some weird stuff with calculations between what's allowed on the backend, what the uploader parses, and what it reports, so we have a mix of everything.

It would be great to move everything to MB instead of MiB, so that numbers are more legible as you mentioned. If I recall correctly, one of the reasons to convert to MiB was because that way it was easier to stay below the max file size limit. What should've happened, is to increase a few bytes on the max allowed size instead.

Right now, this is really low priority, so if this is something you would like to attempt to contribute, you are more than welcome to open a PR to take care of it.
