### ISSUE TITLE
[BUG] Unicode Support

### ISSUE THREAD

**Issue by SleepingPanda** [chibisafe/chibisafe#537]
**Is your feature request related to a problem? Please describe.**
Original Name with different encoding appear garbled

**Describe the solution you'd like**
I would like the addition of unicode support for use in Original Name

**Additional context**
![firefox_SbmnHq9Y79](https://github.com/chibisafe/chibisafe/assets/5846561/fcdaacb2-8e63-45d3-ab15-b31f0b8cfc66)

**Comment by Pitu** [comment]
@SleepingPanda thank you for your report. Could you by any chance share the original filename here?

**Comment by xylonx** [comment]
I have found the problem. It is caused by character set problem. Chibisafe use https://github.com/chibisafe/uploader as its multipart form uploader, which replies on busboy. The default character set for multipart forms is `latin1` in Busboy
I have sent the pr https://github.com/chibisafe/uploader/pull/11 for repo uploader to manually set charset to utf8 for multipart form.
After fixing it locally, I get the correct utf8 filename presentation.

<img width="740" alt="Snipaste_2024-02-08_21-09-36" src="https://github.com/chibisafe/chibisafe/assets/60178952/c1dbee86-2d6e-46b8-b284-4e6a54729e97">

**Comment by Pitu** [comment]
> After fixing it locally, I get the correct utf8 filename presentation.

You legend, I'll take a look today and make a new release after testing it

**Comment by Pitu** [comment]
Released 🎉

**Comment by 7zx** [comment]
Just want to inform that this issue has come back after the recent updates to Chibisafe.

**Comment by Pitu** [comment]
Fixed in latest deployment https://github.com/chibisafe/chibisafe/commit/d4aff91a925c62a849d57fb0e364f2e243a9d5dc
