### ISSUE TITLE
[FEATURE REQUEST] Better user management

### ISSUE THREAD

**Issue by stellarorion** [chibisafe/chibisafe#538]
**Is your feature request related to a problem? Please describe.**
I cannot completely remove a user, I can only "disable them".

**Describe the solution you'd like**
I would love if I could delete users completely from the admin panel. Also an optional setting for users to allow them to disable their own account would be neat as well. Allowing users only to disable their account would be useful in case of needing to recover their files. For example if one user uploaded malware to the server and "deleted" their account. Of course they can just permanently delete the file themselves but just a food for thought

**Additional context**
none

**Comment by Pitu** [comment]
Thanks for opening this issue.
For the time being there are no plans on letting users close their own accounts.
When it comes to removing users, we went with the decision of deactivating them instead of deleting for database consistency. If you were to delete a user and not purge them, the association with files, albums, quarantined files, etc would become quite hectic to keep track of. 

I'll think about it a bit more but I don't see this being a thing for the time being.

**Comment by SleepingPanda** [comment]
Please consider this.
