### ISSUE TITLE
Preserve original file names in the `content-disposition` HTTP header

### ISSUE THREAD

**Issue by HT-7** [chibisafe/chibisafe#685]
**Is your feature request related to a problem? Please describe.**
Currently, Chibisafe only serves randomized meaningless file names. The original file name is preserved internally and visible to the uploader and to site administators only.

**Describe the solution you'd like**
Serve files with a `content-disposition` HTTP header which tells the browser which name it should be saved with. 

**Additional context**
The content-disposition HTTP header does not work just for downloads, but also for inline files that are previewed in the browser, such as pictures. For example, YouTube channel banners have `content-disposition: inline; filename="channels4_banner.jpg"`, so that file name shows in the title and as a pre-filled file name in the "Save as" window.

**Comment by Pitu** [comment]
Since exposing it could be a potential security risk, downloading the original file with its original name requires knowing the uuid of the file. For this purpose, chibisafe already exposes an endpoint that the owner of a file can use to share a download link that preserves the original filename.

https://chibisafe.app/docs#tag/files/get/api/file/{uuid}/download
